version: '3'
services: 
  dvwa:
    build: ./dvwa
    networks:
      proxynet:
        ipv4_address: 172.16.1.2


  https-proxy:
    build: ./nginx_proxy
    ports:
      - "443:443"
    networks:
      proxynet:
        ipv4_address: 172.16.1.3

  modsec:
    tty: true
    build: ./modsecurity
    ports:
      - "8080:8080"
    networks:
      proxynet:
        ipv4_address: 172.16.1.4

networks:
  proxynet:
    ipam:
      config:
        - subnet: 172.16.1.0/24
        
